CREATE DATABASE QLKB 
USE QLKB 

CREATE TABLE BENHNHAN(
	MABN CHAR(5) PRIMARY KEY,
	HOTENBN NVARCHAR(50),
	NGAYSINH SMALLDATETIME, 
	CCCD NVARCHAR(12),
	SOBHYT NVARCHAR(15),
	DIACHI NVARCHAR(100) 
	)

CREATE TABLE BACSI (
	MABS CHAR(5) PRIMARY KEY,
	HOTENBS NVARCHAR(50),
	NGAYBDLV SMALLDATETIME,
	CHUYENKHOA NVARCHAR(50)
	)

CREATE TABLE KHAMBENH(
	MAKB CHAR(5) PRIMARY KEY,
	MABN CHAR(5) FOREIGN KEY REFERENCES BENHNHAN(MABN),
	MABS CHAR(5) FOREIGN KEY REFERENCES BACSI(MABS),
	NGAYKHAM SMALLDATETIME,
	TRIEUCHUNG NVARCHAR(255),
	KETLUAN NVARCHAR(255),
	TAIKHAM INT
	)

CREATE TABLE THUOC (
	MATHUOC CHAR(5) PRIMARY KEY,
	TENTHUOC NVARCHAR(50),
	LOAITHUOC NVARCHAR(50),
	DVT NVARCHAR(20),
	DONGIA MONEY
	)

CREATE TABLE DONTHUOC (
	MADT CHAR(5) PRIMARY KEY,
	MAKB CHAR(5) FOREIGN KEY REFERENCES KHAMBENH(MAKB),
	TRIGIADT MONEY,
	BHYTCHITRA FLOAT,
	NGAYCAPTHUOC SMALLDATETIME,
	TONGTIENTT MONEY,
	TINHTRANGDT NVARCHAR(30)
	)

CREATE TABLE CHITIETDT (
	MADT CHAR(5) FOREIGN KEY REFERENCES DONTHUOC(MADT),
	MATHUOC CHAR(5) FOREIGN KEY REFERENCES THUOC(MATHUOC),
	SOLUONG INT,
	THANHTIEN MONEY,
	PRIMARY KEY(MADT, MATHUOC)
	)

-- CAU 2 --
ALTER TABLE DONTHUOC 
ADD CONSTRAINT DT_CK CHECK (BHYTCHITRA >= 0 AND BHYTCHITRA <=0.7)

ALTER TABLE DONTHUOC 
ADD CONSTRAINT TT_CK CHECK (TINHTRANGDT IN (N'Đã thanh toán', N'Chưa thanh toán'))

GO 
CREATE TRIGGER MOINE 
ON CHITIETDT
FOR INSERT
AS
BEGIN 
	UPDATE DONTHUOC
	SET TRIGIADT = TRIGIADT + INS.THANHTIEN 
	FROM INSERTED INS --INS la bang tam de luu chi tiet don thuoc moi 
	JOIN DONTHUOC DT ON INS.MADT = DT.MADT  
END

-- CAU 3 --
SELECT BS.MABS, HOTENBS, BN.MABN, HOTENBN
FROM BACSI BS 
JOIN KHAMBENH KB ON BS.MABS = KB.MABS
JOIN BENHNHAN BN ON KB.MABN = BN.MABN 
WHERE CHUYENKHOA = N'Tai mũi họng' AND YEAR(NGAYKHAM) = 2024

SELECT BN.MABN, HOTENBN
FROM BENHNHAN BN
JOIN KHAMBENH KB ON BN.MABN = KB.MAKB 
JOIN DONTHUOC DT ON KB.MAKB = DT.MAKB 
WHERE YEAR(NGAYKHAM) = 2024
EXCEPT 
SELECT BN.MABN, HOTENBN
FROM BENHNHAN BN
JOIN KHAMBENH KB ON BN.MABN = KB.MAKB 
JOIN DONTHUOC DT ON KB.MAKB = DT.MAKB 
WHERE YEAR(NGAYKHAM) = 2024 AND TINHTRANGDT = N'Đã thanh toán' 
AND TONGTIENTT >= 100000

SELECT DT.MADT, KB.MAKB
FROM DONTHUOC DT
JOIN KHAMBENH KB ON DT.MAKB = KB.MAKB
WHERE YEAR(NGAYCAPTHUOC) = 2024 AND TINHTRANGDT = N'Đã thanh toán' AND NOT EXISTS (
	SELECT *
	FROM THUOC 
	WHERE LOAITHUOC = N'Thuốc dị ứng' AND NOT EXISTS (
		SELECT * 
		FROM CHITIETDT CT
		WHERE DT.MADT = CT.MADT 
		AND CT.MATHUOC = THUOC.MATHUOC ))

SELECT BN.MABN, HOTENBN, COUNT(DISTINCT DT.MADT) AS SOLUONG
FROM BENHNHAN BN 
JOIN KHAMBENH KB ON BN.MABN = KB.MABN
JOIN DONTHUOC DT ON KB.MAKB = DT.MAKB
WHERE YEAR(NGAYCAPTHUOC) = 2024 AND TINHTRANGDT = N'Đã thanh toán' 
AND SOBHYT IS NULL
GROUP BY BN.MABN, HOTENBN

SELECT BN.MABN, HOTENBN 
FROM BENHNHAN BN 
JOIN KHAMBENH KB ON BN.MABN = KB.MABN 
JOIN DONTHUOC DT ON KB.MAKB = DT.MAKB 
WHERE YEAR(NGAYCAPTHUOC) = 2024 
AND TINHTRANGDT = N'Đã thanh toán' 
GROUP BY BN.MABN, HOTENBN 
HAVING SUM(TONGTIENTT) < 100000 AND COUNT(DISTINCT KB.MAKB) = (
	SELECT MIN(LANKHAM) 
	FROM (
		SELECT SUM(DISTINCT KB.MAKB) AS LANKHAM, BN.MABN, HOTENBN
		FROM BENHNHAN BN 
		JOIN KHAMBENH KB ON BN.MABN = KB.MABN 
		JOIN DONTHUOC DT ON KB.MAKB = DT.MAKB
		GROUP BY BN.MABN, HOTENBN ) AS BANGLANKHAMMIN)




