CREATE DATABASE QLPT102
USE QLPT102

CREATE TABLE PHONGTRO (
	MaPT CHAR(5) PRIMARY KEY,
	TenPT NVARCHAR(50),
	DienTich FLOAT,
	GiaPT MONEY,
	TinhTrangPT nvarchar(20)
	)

CREATE TABLE CUDAN (
	MaCD CHAR(5) PRIMARY KEY,
	HoTen NVARCHAR(50),
	CCCD NVARCHAR(12),
	DiaChi NVARCHAR(100),
	SoDT varchar(15),
	NgayThue smalldatetime,
	TrangThaiCD nvarchar(15)
	)

CREATE TABLE HOPDONG (
	MaHD CHAR(5) PRIMARY KEY,
	MaCD CHAR(5) FOREIGN KEY REFERENCES CUDAN(MaCD),
	MaPT CHAR(5) FOREIGN KEY REFERENCES PHONGTRO(MaPT),
	NgayKy smalldatetime,
	NgayHetHan smalldatetime,
	TrangThaiHD nvarchar(20)
	)

CREATE TABLE DICHVU (
	MaDV CHAR(5) PRIMARY KEY,
	TenDV nvarchar(50),
	DonGia money
	)

CREATE TABLE PHIEUTINHTIEN (
	MaPTT CHAR(5) PRIMARY KEY,
	MaHD CHAR(5) FOREIGN KEY REFERENCES HOPDONG(MaHD),
	SoTienDichVu MONEY,
	SoTienThuePT MONEY,
	TongTienTT MONEY,
	NgayTinhTien smalldatetime,
	TinhTrangTT nvarchar(20),
	PhuongThucTT nvarchar(20)
	)

CREATE TABLE CHITIETTTDV (
	MaPTT CHAR(5) FOREIGN KEY REFERENCES PHIEUTINHTIEN(MaPTT),
	MaDV CHAR(5) FOREIGN KEY REFERENCES DICHVU(MaDV),
	ChiSoDV float,
	ThanhTien money,
	PRIMARY KEY (MaPTT, MaDV)
	)

-- CAU 2.1 
ALTER TABLE PHONGTRO 
ADD CONSTRAINT GiaPT_CK CHECK (GiaPT >= 500000 AND GiaPT <= 20000000)

-- CAU 2.2
ALTER TABLE CUDAN 
ADD CONSTRAINT CD_CK CHECK (TrangThaiCD IN (N'Đang ở', N'Đã rời đi')

-- CAU 2.3
GO 
CREATE TRIGGER TG23
ON CHITIETTTDV
FOR INSERT, UPDATE 
AS
BEGIN 
	UPDATE CHITIETTTDV
	SET ThanhTien = ChiSoDV * DonGia
	FROM inserted INS 
	WHERE 

END 

-- CAU 3.1 
SELECT CD.MaCD, HoTen, PT.MaPT, TenPT
FROM CUDAN CD
JOIN HOPDONG HD ON CD.MaCD = HD.MaCD
JOIN PHONGTRO PT ON HD.MaPT = PT.MaPT 
WHERE YEAR(NgayHetHan) = 2024 AND TrangThaiHD = N'Đã hết hạn'

-- CAU 3.2 
SELECT HD.MaHD, HD.MaPT
FROM HOPDONG HD 
JOIN PHIEUTINHTIEN PTT ON HD.MaHD = PTT.MaHD
JOIN CHITIETTTDV CT ON PTT.MaPTT = CT.MaPTT
WHERE YEAR(NgayTinhTien) = 2024 
AND ChiSoDV >= 5 AND TrangThaiHD = N'Đã thanh toán' 

-- CAU 3.3
SELECT DV.MaDV, TenDV
FROM DICHVU DV
JOIN CHITIETTTDV CT ON DV.MaDV = CT.MaDV
JOIN PHIEUTINHTIEN PTT ON CT.MaPTT = PTT.MaPTT






