CREATE DATABASE THUCHANH2425
USE THUCHANH2425

-- DE 101 -- 
-- CAU 1 --
CREATE TABLE PHONGTRO (
	MAPT CHAR(5) PRIMARY KEY,
	TENPT NVARCHAR(50),
	DIENTICH FLOAT,
	GIAPT MONEY,
	TINHTRANGPT NVARCHAR(20)
)

CREATE TABLE CUDAN (
	MACD CHAR(5) PRIMARY KEY,
	HOTEN NVARCHAR(50),
	CCCD NVARCHAR(12),
	SODT VARCHAR(15),
	NGAYTHUE SMALLDATETIME,
	TRANGTHAICD NVARCHAR(15)
)

CREATE TABLE HOPDONG (
	MAHD CHAR(5) PRIMARY KEY,
	MACD CHAR(5),
	MAPT CHAR(5),
	NGAYKY SMALLDATETIME,
	NGAYHETHAN SMALLDATETIME,
	TRANGTHAIHD NVARCHAR(20)
	)

CREATE TABLE DICHVU (
	MADV CHAR(5) PRIMARY KEY,
	TENDV NVARCHAR(50),
	DONGIA MONEY
	)

CREATE TABLE PHIEUTINHTIEN (
	MAPTT CHAR(5) PRIMARY KEY,
	MAHD CHAR(5),
	SOTIENDICHVU MONEY,
	SOTIENTHUEPT MONEY,
	TONGTIENTT MONEY,
	NGAYTINHTIEN SMALLDATETIME,
	TINHTRANGTT NVARCHAR(20),
	PHUONGTHUCTT NVARCHAR(20)
	)

CREATE TABLE CHITIETTTDV (
	MAPTT CHAR(5) PRIMARY KEY,
	MADV CHAR(5),
	CHISODV FLOAT,
	THANHTIEN MONEY
	)

ALTER TABLE HOPDONG 
ADD CONSTRAINT FK_HOPDONG_PHONGTRO FOREIGN KEY (MAPT) REFERENCES PHONGTRO(MAPT)

ALTER TABLE HOPDONG 
ADD CONSTRAINT FK_HOPDONG_CUDAN FOREIGN KEY(MACD) REFERENCES CUDAN(MACD)

ALTER TABLE PHIEUTINHTIEN 
ADD CONSTRAINT FK_PHIEUTINHTIEN_HOPDONG FOREIGN KEY(MAHD) REFERENCES HOPDONG(MAHD)

ALTER TABLE CHITIETTTDV 
ADD CONSTRAINT FK_CHITIETTTDV_DICHVU FOREIGN KEY (MADV) REFERENCES DICHVU(MADV)

ALTER TABLE CHITIETTTDV 
ADD CONSTRAINT FK_CHITIETTTDV_PHIEUTINHTIEN FOREIGN KEY (MAPTT) REFERENCES PHIEUTINHTIEN(MAPTT)

-- CAU 2 -- 
ALTER TABLE PHONGTRO 
ADD CONSTRAINT DIENTICH_CK CHECK (DIENTICH >= 10 AND DIENTICH <= 50)

ALTER TABLE PHIEUTINHTIEN
ADD CONSTRAINT TINHTRANGTT_CK CHECK (TINHTRANGTT IN (N'Chưa thanh toán',N'Đã thanh toán'))

GO
CREATE TRIGGER CHITIETMOI
ON CHITIETTTDV
FOR INSERT
AS 
BEGIN 
	UPDATE CHITIETTTDV
	SET THANHTIEN = INS.CHISODV * DICHVU.DONGIA
	FROM INSERTED INS
	JOIN CHITIETTTDV CT ON INS.MAPTT = CT.MAPTT AND INS.MADV = CT.MADV
	JOIN DICHVU ON INS.MADV = DICHVU.MADV 
END

-- CAU 3 --
SELECT PHONGTRO.MAPT, TENPT, CUDAN.MACD, HOTEN 
FROM PHONGTRO
JOIN HOPDONG ON PHONGTRO.MAPT = HOPDONG.MAPT 
JOIN CUDAN ON HOPDONG.MACD = CUDAN.MACD
WHERE GIAPT >= 5000000 AND YEAR(NGAYKY) = 2024 

SELECT DICHVU.MADV, TENDV 
FROM DICHVU
JOIN CHITIETTTDV CT ON DICHVU.MADV = CT.MADV
JOIN PHIEUTINHTIEN PTT ON CT.MAPTT = PTT.MAPTT 
JOIN HOPDONG ON PTT.MAHD = HOPDONG.MAHD 
WHERE HOPDONG.MAHD = 'HD0002'AND YEAR(NGAYTINHTIEN) = 2024 
	AND MONTH(NGAYTINHTIEN) = 11
INTERSECT 
SELECT DICHVU.MADV, TENDV 
FROM DICHVU
JOIN CHITIETTTDV CT ON DICHVU.MADV = CT.MADV
JOIN PHIEUTINHTIEN PTT ON CT.MAPTT = PTT.MAPTT 
JOIN HOPDONG ON PTT.MAHD = HOPDONG.MAHD 
WHERE HOPDONG.MAHD = 'HD0002'AND YEAR(NGAYTINHTIEN) = 2024 
	AND MONTH(NGAYTINHTIEN) = 12

SELECT PTT.MAPTT, MAHD
FROM PHIEUTINHTIEN PTT
WHERE YEAR(NGAYTINHTIEN) = 2024 AND NOT EXISTS (
	SELECT * 
	FROM DICHVU 
	WHERE DONGIA < 150000 AND NOT EXISTS (
		SELECT * 
		FROM CHITIETTTDV CT
		WHERE PTT.MAPTT = CT.MAPTT 
		AND CT.MADV = DICHVU.MADV ))

SELECT COUNT(DISTINCT MAPTT) AS SOLUONG, HOPDONG.MAHD, CUDAN.MACD
FROM PHIEUTINHTIEN PTT
JOIN HOPDONG ON PTT.MAHD = HOPDONG.MAHD 
JOIN CUDAN ON HOPDONG.MACD = CUDAN.MACD
WHERE PHUONGTHUCTT = N'Chuyển khoản' 
	AND YEAR(NGAYTINHTIEN) = 2024
	AND TINHTRANGTT = N'Đã thanh toán'
GROUP BY HOPDONG.MAHD, CUDAN.MACD 

SELECT CUDAN.MACD, HOTEN 
FROM CUDAN 
JOIN HOPDONG ON CUDAN.MACD = HOPDONG.MACD 
JOIN PHIEUTINHTIEN PTT ON HOPDONG.MAHD = PTT.MAHD 
WHERE YEAR(NGAYTINHTIEN) = 2024 AND TINHTRANGTT = N'Đã thanh toán'
GROUP BY CUDAN.MACD, HOTEN
HAVING SUM(TONGTIENTT) > 15000000
AND COUNT(DISTINCT HOPDONG.MAHD) = (
	SELECT MAX(LANKI)
	FROM (
		SELECT HOPDONG.MACD, HOTEN, COUNT(DISTINCT HOPDONG.MAHD) AS LANKI
		FROM HOPDONG
		JOIN CUDAN ON HOPDONG.MACD = CUDAN.MACD
		GROUP BY HOPDONG.MACD, HOTEN ) AS BANGTAM )