CREATE DATABASE QLPT
USE QLPT

CREATE TABLE PHONGTRO (
	MAPT CHAR(5) PRIMARY KEY,
	TENPT NVARCHAR(50),
	DIENTICH FLOAT,
	GIAPT MONEY,
	TINHTRANGPT NVARCHAR(20)
)
ALTER TABLE PHONGTRO ADD LOAIPT NVARCHAR(15) 

CREATE TABLE CUDAN (
	MACD CHAR(5) PRIMARY KEY,
	HOTEN NVARCHAR(50),
	CCCD NVARCHAR(12),
	SODT VARCHAR(15),
	TRANGTHAICD NVARCHAR(15)
)
ALTER TABLE CUDAN ADD DIACHI NVARCHAR(100)
ALTER TABLE CUDAN DROP COLUMN NGAYTHUE

CREATE TABLE HOPDONG (
	MAHD CHAR(5) PRIMARY KEY,
	MACD CHAR(5) FOREIGN KEY REFERENCES CUDAN(MACD),
	MAPT CHAR(5) FOREIGN KEY REFERENCES PHONGTRO(MAPT),
	NGAYKY SMALLDATETIME,
	NGAYHETHAN SMALLDATETIME,
	TRANGTHAIHD NVARCHAR(20)
	)

CREATE TABLE DICHVU (
	MADV CHAR(5) PRIMARY KEY,
	TENDV NVARCHAR(50),
	DONGIA MONEY
	)

CREATE TABLE PHIEUTINHTIEN (
	MAPTT CHAR(5) PRIMARY KEY,
	MAHD CHAR(5) FOREIGN KEY REFERENCES HOPDONG(MAHD),
	SOTIENDICHVU MONEY,
	SOTIENTHUEPT MONEY,
	TONGTIENTT MONEY,
	NGAYTINHTIEN SMALLDATETIME,
	TINHTRANGTT NVARCHAR(20),
	PHUONGTHUCTT NVARCHAR(20)
	)

CREATE TABLE CHITIETTTDV (
	MAPTT CHAR(5) PRIMARY KEY FOREIGN KEY REFERENCES PHIEUTINHTIEN(MAPTT),
	MADV CHAR(5) FOREIGN KEY REFERENCES DICHVU(MADV),
	CHISODV FLOAT,
	THANHTIEN MONEY
	)

-- CAU 2 --
ALTER TABLE HOPDONG 
ADD CONSTRAINT HD_CK CHECK (NGAYKY <= NGAYHETHAN)

ALTER TABLE PHONGTRO
ADD CONSTRAINT PT_CK CHECK (TINHTRANGPT IN (N'Trống',N'Đã cho thuê'))

GO 
CREATE TRIGGER MOI 
ON CHITIETTTDV 
FOR DELETE
AS
BEGIN 
	UPDATE PHIEUTINHTIEN 
	SET SOTIENDICHVU = SOTIENDICHVU - DE.THANHTIEN
	FROM DELETED DE
	JOIN PHIEUTINHTIEN PTT ON DE.MAPTT = PTT.MAPTT 
END 

-- CAU 3 --
SELECT PHONGTRO.MAPT, TENPT, PTT.MAPTT, PTT.TONGTIENTT
FROM PHONGTRO 
JOIN HOPDONG ON PHONGTRO.MAPT = HOPDONG.MAPT 
JOIN PHIEUTINHTIEN PTT ON HOPDONG.MAHD = PTT.MAHD 
WHERE YEAR(NGAYTINHTIEN) = 2024

SELECT CUDAN.MACD, HOTEN 
FROM CUDAN 
JOIN HOPDONG ON CUDAN.MACD = HOPDONG.MACD 
JOIN PHONGTRO ON HOPDONG.MAPT = PHONGTRO.MAPT 
WHERE DIENTICH > 20 AND YEAR(NGAYKY) = 2024 AND LOAIPT = 'Kiot' 
INTERSECT 
SELECT CUDAN.MACD, HOTEN 
FROM CUDAN 
JOIN HOPDONG ON CUDAN.MACD = HOPDONG.MACD 
JOIN PHONGTRO ON HOPDONG.MAPT = PHONGTRO.MAPT 
WHERE DIENTICH > 20 AND YEAR(NGAYKY) = 2024 AND LOAIPT = 'Có gác xép'

SELECT PTT.MAPTT, MAHD 
FROM PHIEUTINHTIEN PTT 
WHERE TONGTIENTT > 2000000 AND PHUONGTHUCTT = N'Tiền mặt'
AND NOT EXISTS ( 
	SELECT * 
	FROM DICHVU 
	WHERE DONGIA <= 50000 AND NOT EXISTS (
		SELECT * 
		FROM CHITIETTTDV CT
		WHERE PTT.MAPTT = CT.MAPTT AND CT.MADV = DICHVU.MADV )) 

SELECT CUDAN.MACD, HOTEN, COUNT(DISTINCT MAHD) AS SOLUONGHD
FROM CUDAN 
JOIN HOPDONG ON CUDAN.MACD = HOPDONG.MACD 
WHERE TRANGTHAIHD = N'Đã hết hạn' AND YEAR(HOPDONG.NGAYHETHAN) = 2024 
GROUP BY CUDAN.MACD, HOTEN 

SELECT HOPDONG.MAHD 
FROM HOPDONG 
JOIN PHIEUTINHTIEN PTT ON HOPDONG.MAHD = PTT.MAHD
JOIN CHITIETTTDV CT ON PTT.MAPTT = CT.MAPTT
JOIN DICHVU DV ON CT.MADV = DV.MADV
WHERE TINHTRANGTT = N'Đã thanh toán' AND TENDV = N'Điện'
GROUP BY HOPDONG.MAHD 
HAVING COUNT(DISTINCT PTT.MAPTT) >= 2 
AND SUM(CHISODV) = (
	SELECT MIN(DIENIT) 
	FROM (
		SELECT SUM(CHISODV) AS DIENIT, HD.MAHD
		FROM HOPDONG HD
		JOIN PHIEUTINHTIEN PTT ON HD.MAHD = PTT.MAHD
		JOIN CHITIETTTDV CT ON PTT.MAPTT = CT.MAPTT 
		JOIN DICHVU DV ON CT.MADV = DV.MADV
		WHERE TENDV = N'Điện' AND TINHTRANGTT = N'Đã thanh toán'
		GROUP BY HD.MAHD 
		) AS BANGTIMDIENITNHAT )

		



