CREATE DATABASE ONTHI03
USE ONTHI03

CREATE TABLE KHACHHANG (
	MAKH VARCHAR(5) PRIMARY KEY,
	TENKH VARCHAR(50),
	DIACHI VARCHAR(30),
	LOAIKH VARCHAR(20)
)

CREATE TABLE LOAICAY (
	MALC VARCHAR(5) PRIMARY KEY,
	TENLC VARCHAR(20),
	XUATXU VARCHAR(20),
	GIA MONEY 
)

CREATE TABLE HOADON (
	SOHD INT PRIMARY KEY,
	NGHD SMALLDATETIME,
	MAKH VARCHAR(5),
	KHUYENMAI INT
)

CREATE TABLE CTHD (
	SOHD INT,
	MALC VARCHAR(5),
	SOLUONG INT,
	PRIMARY KEY (SOHD, MALC)
)

ALTER TABLE HOADON 
ADD CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)

ALTER TABLE CTHD 
ADD CONSTRAINT FK_CTHD_HOADON FOREIGN KEY (SOHD) REFERENCES HOADON(SOHD)

ALTER TABLE CTHD 
ADD CONSTRAINT FK_CTHD_LOAICAY FOREIGN KEY (MALC) REFERENCES LOAICAY(MALC)

INSERT INTO KHACHHANG (MAKH, TENKH, DIACHI, LOAIKH)
VALUES 
('KH01', N'Liz Kim Cương', N'Hà Nội', N'Vãng lai'),
('KH02', N'Ivone Dieu Linh', N'Đà Nẵng', N'Thường xuyên'),
('KH03', N'Emma Nhat Khanh', N'TP.HCM', N'Vãng lai');

INSERT INTO LOAICAY (MALC, TENLC, XUATXU, GIA) VALUES
('LC01', N'Xương rồng tai thỏ', N'Mexico', 180000),
('LC02', N'Sen thạch ngọc', N'Anh', 300000),
('LC03', N'Ba màu râu', N'Nam Phi', 270000);

INSERT INTO HOADON (SOHD, NGHD, MAKH, KHUYENMAI) VALUES
('00001', '2017-11-22', 'KH01', 5),
('00002', '2017-12-04', 'KH03', 5),
('00003', '2017-12-10', 'KH02', 10);

INSERT INTO CTHD (SOHD, MALC, SOLUONG) VALUES
('00001', 'LC01', 1),
('00001', 'LC02', 2),
('00003', 'LC03', 5);


-- CAU 5 --
SELECT HOADON.SOHD, KHUYENMAI
FROM CTHD
JOIN HOADON ON CTHD.SOHD = HOADON.SOHD 
WHERE MONTH(NGHD) >= 9 AND MONTH(NGHD) <= 12 AND YEAR(NGHD) = 2017
GROUP BY HOADON.SOHD 
HAVING COUNT(DISTINCT HOADON.SOHD) = (SELECT COUNT(DISTINCT SOHD) 
	FROM CTHD 
	WHERE CTHD.SOHD = HOADON.SOHD 
	AND KHUYENMAI > 0 )
ORDER BY HOADON.KHUYENMAI ASC 

-- CAU 06 --
SELECT MIN(CTHD.MALC)
FROM LOAICAY 
JOIN CTHD ON LOAICAY.MALC = CTHD.MALC
JOIN HOADON ON CTHD.SOHD = HOADON.SOHD
WHERE MONTH(NGHD) = 12 

-- CAU 07 --
SELECT MALC 
FROM CTHD
JOIN HOADON ON CTHD.SOHD = HOADON.SOHD 
JOIN KHACHHANG ON HOADON.MAKH = KHACHHANG.MAKH 
WHERE LOAIKH = N'Thường xuyên' AND LOAIKH = N'Vãng lai'


SELECT MAKH 
FROM HOADON 
WHERE NOT EXISTS (SELECT * 
	FROM LOAICAY
	WHERE NOT EXISTS (SELECT * 
		FROM CTHD
		WHERE LOAICAY.MALC = CTHD.MALC
		AND CTHD.SOHD = CTHD.SOHD ))
