CREATE DATABASE ONTHITHUCHANH1
USE ONTHITHUCHANH1

-- DE 2018 - 2019 --
-- CAU 01 TAO BANG, TAO RANG BUOC KHOA CHINH, KHOA NGOAI --
CREATE TABLE KETQUA (
	MAKETQUA char(4) PRIMARY KEY,
	TENKETQUA varchar(20),
)

CREATE TABLE HOCVIEN ( 
	MAHV char(4) PRIMARY KEY,
	HOTEN varchar(30), 
	NGSINH smalldatetime,
	DIACHI varchar(30),
	EMAIL varchar(30),
	SDT varchar(15),
	MAKETQUA char(4),
) 

CREATE TABLE GIAOVIEN (
	MAGV char(4) PRIMARY KEY,
	HOTEN varchar(30),
	NGSINH smalldatetime,
	NGVL smalldatetime, 
)

CREATE TABLE XE (
	MAXE CHAR(4) PRIMARY KEY,
	BIENSO VARCHAR(10),
	TENLOAIXE VARCHAR(20),
)

CREATE TABLE BAIDAY (
	MABAIDAY CHAR(4) PRIMARY KEY,
	NGAYDAY SMALLDATETIME,
	SOGIO INT,
	GIA MONEY,
	MAHV CHAR(4),
	MAGV CHAR(4),
	MAXE CHAR(4),
)

ALTER TABLE HOCVIEN 
ADD CONSTRAINT FK_HOCVIEN_KETQUA FOREIGN KEY (MAKETQUA) REFERENCES KETQUA(MAKETQUA)

ALTER TABLE BAIDAY 
ADD CONSTRAINT FK_BAIDAY_HOCVIEN FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV)

ALTER TABLE BAIDAY
ADD CONSTRAINT FK_BAIDAY_GIAOVIEN FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE BAIDAY 
ADD CONSTRAINT FK_BAIDAY_XE FOREIGN KEY (MAXE) REFERENCES XE(MAXE)

-- CAU 1.2 THEM DU LIEU VAO BANG HOCVIEN, GIAOVIEN, XE, BAIDAY -- 
INSERT INTO HOCVIEN (MAHV, HOTEN, NGSINH, DIACHI, EMAIL, SDT, MAKETQUA) 
VALUES
('MASO 777 ', 'DANG VAN KHANH','28/05/2006','KHUB','777@GM','0123456','0777');

INSERT INTO GIAOVIEN (MAGV, HOTEN, NGSINH, NGVL)
VALUES 
('123','ABC','28/05/2000','28/05/2025');

INSERT INTO XE (MAXE, BIENSO, TENLOAIXE)
VALUES
('BAC123','94F4-1111','SUZUKI');

INSERT INTO BAIDAY (MABAIDAY, NGAYDAY, SOGIO, GIA, MAHV, MAGV, MAXE) 
VALUES 
('BAIDAY1','25/06/2025','14','200000','MASO 777','123','BAC123');

--CAU 1.3 CAP NHAT 1 DONG DU LIEU VAO BANG BAIDAY --
UPDATE BAIDAY
SET GIA = GIA *1.5
WHERE SOGIO > 10

-- CAU 2.1 TEN KETQUA CHI LA DAU/ROT --
ALTER TABLE KETQUA 
ADD CONSTRAINT TENKETQUA_CK CHECK (TENKETQUA IN ('DAU','ROT'))

ALTER TABLE BAIDAY
ADD CONSTRAINT GIA_CK CHECK (GIA < 5 )

-- CAU 2.2 TRIGGER --
CREATE TRIGGER BAIDAYHEHE
ON BAIDAY
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS (
		SELECT *
		FROM inserted
		JOIN GIAOVIEN ON inserted.MAGV = GIAOVIEN.MAGV 
		WHERE GIAOVIEN.NGVL >= inserted.NGAYDAY )
	BEGIN 
		ROLLBACK TRANSACTION
	END
END 

-- CAU 3 -- 
SELECT XE.MAXE, BIENSO
FROM XE, BAIDAY
WHERE XE.MAXE = BAIDAY.MAXE
AND NGAYDAY = '5/5/2018'

SELECT TOP 1 MABAIDAY, NGAYDAY 
FROM BAIDAY
GROUP BY MABAIDAY, NGAYDAY
ORDER BY SOGIO ASC

-- Duoc su dung trong ngay X nhung khong duoc trong ngay Y --
SELECT XE.MAXE, BIENSO 
FROM XE
JOIN BAIDAY ON XE.MAXE = BAIDAY.MAXE
WHERE NGAYDAY = '1/1/2018'
EXCEPT -- KHONG CO NGOAC 
SELECT XE.MAXE, BIENSO 
FROM XE
JOIN BAIDAY ON XE.MAXE = BAIDAY.MAXE
WHERE NGAYDAY = '2/1/2018'

SELECT GIAOVIEN.MAGV, HOTEN
FROM GIAOVIEN
JOIN BAIDAY ON GIAOVIEN.MAGV = BAIDAY.MAGV
WHERE MONTH(NGAYDAY) = 7 AND YEAR(NGAYDAY) = 2017 
GROUP BY GIAOVIEN.MAGV, HOTEN 
HAVING COUNT(DISTINCT MABAIDAY) < 10

SELECT HOCVIEN.MAHV, HOCVIEN.HOTEN 
FROM HOCVIEN 
JOIN BAIDAY ON HOCVIEN.MAHV = BAIDAY.MAHV
JOIN GIAOVIEN ON BAIDAY.MAGV = GIAOVIEN.MAGV 
WHERE MONTH(HOCVIEN.NGSINH) = 6
GROUP BY HOCVIEN.MAHV, HOCVIEN.HOTEN 
HAVING 
	COUNT(DISTINCT GIAOVIEN.MAGV) = (SELECT COUNT(*)
		FROM GIAOVIEN 
		WHERE YEAR(NGSINH) = 1960);

SELECT GIAOVIEN.MAGV, GIAOVIEN.HOTEN, COUNT(DISTINCT MABAIDAY) AS SOLUONG
FROM BAIDAY
JOIN GIAOVIEN ON BAIDAY.MAGV = GIAOVIEN.MAGV 
GROUP BY GIAOVIEN.MAGV, GIAOVIEN.HOTEN
