CREATE DATABASE ONTHITHUCHANH
USE ONTHITHUCHANH

-- 2021-2022 DE THI 01 --
-- CAU 1 CAI DAT LUOC DO CSDL -- 
CREATE TABLE NHANVIEN (
	MANV varchar(3) primary key,
	HOTEN varchar(40),
	NGSINH smalldatetime, 
	PHAI varchar(3),
	DIACHI varchar(50),
	MAPHG varchar(2),
	LUONG money
)

CREATE TABLE PHONGBAN (
	MAPHG varchar(2) PRIMARY KEY,
	TENPHG varchar(50),
	TRGPHG varchar(3),
	NGNC smalldatetime
)

CREATE TABLE PHONGBAN (
	MAPHG varchar(2) PRIMARY KEY,
	TENPHG varchar(50),
	TRGPHG varchar(3) FOREIGN KEY REFERENCES NHANVIEN(MANV),
	NGNC smalldatetime
)

CREATE TABLE DEAN (
	MADA varchar(5) PRIMARY KEY,
	TENDA varchar(50),
	DDIEM_DA varchar(50),
	MAPHG varchar(2),
	NGBD_DK smalldatetime,
	NGKT_DK smalldatetime
)

CREATE TABLE PHANCONG (
	MANV varchar(3),
	MADA varchar(5),
	THOIGIAN int,
	PRIMARY KEY (MANV, MADA)
)

ALTER TABLE PHONGBAN 
ADD CONSTRAINT FK_PHONGBAN_NHANVIEN FOREIGN KEY (TRGPHG) REFERENCES NHANVIEN(MANV) 

ALTER TABLE NHANVIEN 
ADD CONSTRAINT FK_NHANVIEN_PHONGBAN FOREIGN KEY (MAPHG) REFERENCES PHONGBAN(MAPHG)

ALTER TABLE DEAN 
ADD CONSTRAINT FK_DEAN_PHONGBAN FOREIGN KEY (MAPHG) REFERENCES PHONGBAN(MAPHG)

ALTER TABLE PHANCONG 
ADD CONSTRAINT FK_PHANCONG_DEAN FOREIGN KEY (MADA) REFERENCES DEAN(MADA)

ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PHANCONG_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)

-- CAU 2 THUC HIEN RANG BUOC TOAN VEN --
ALTER TABLE NHANVIEN ADD CONSTRAINT LUONG_CK CHECK ( MAPHG = 'NC' AND LUONG > 20000000 )

CREATE TRIGGER NGAYBD_NGSINH 
ON PHANCONG
FOR INSERT, UPDATE 
AS 
BEGIN
    IF EXISTS (
        SELECT *
        FROM INSERTED INS
			JOIN NHANVIEN ON INS.MANV = NHANVIEN.MANV
			JOIN DEAN ON INS.MADA = DEAN.MADA
        WHERE DEAN.NGBD_DK <= NHANVIEN.NGSINH
    )
    BEGIN
        ROLLBACK TRANSACTION
    END
END 

-- CAU 03 -- 
-- TENPHG co LUONG trungbinh >=24000000 sap xep theo thu tu phong ban giam dan
SELECT PHONGBAN.TENPHG, AVG(LUONG) AS LUONGTRUNGBINH
FROM PHONGBAN 
JOIN NHANVIEN ON PHONGBAN.MAPHG = NHANVIEN.MAPHG
GROUP BY PHONGBAN.TENPHG
HAVING AVG(LUONG) >= 24000000
ORDER BY PHONGBAN.TENPHG DESC

-- HOTEN tham gia de an cua phong 'Nghien Cuu' co DIADIEM = 'HANOI'
SELECT NHANVIEN.HOTEN
FROM NHANVIEN 
JOIN PHANCONG ON NHANVIEN.MANV = PHANCONG.MANV
JOIN DEAN ON PHANCONG.MADA = DEAN.MADA 
JOIN PHONGBAN ON DEAN.MAPHG = PHONGBAN.MAPHG 
WHERE TENPHG = 'Nghien Cuu' AND DDIEM_DA = 'HANOI'

-- HOTEN va SOLUONGDEAN ma nhan vien do tham gia
SELECT NHANVIEN.HOTEN, COUNT(DISTINCT DEAN.MADA) AS SOLUONGDEAN
FROM NHANVIEN 
JOIN PHANCONG ON NHANVIEN.MANV = PHANCONG.MANV
JOIN DEAN ON PHANCONG.MADA = DEAN.MADA 
GROUP BY NHANVIEN.HOTEN

-- HOTEN chi tham gia dean do 'Nghien Cuu' chu tri
-- Dung EXCEPT 
-- Dung NOT IN 

SELECT NHANVIEN.HOTEN
FROM NHANVIEN 
JOIN PHONGBAN ON NHANVIEN.MAPHG = PHONGBAN.MAPHG 
WHERE MANV NOT IN (SELECT TENPHG 
	FROM PHONGBAN 
	WHERE TENPHG IN ('Quan Ly','Dieu Hanh')
	) 

-- HOTEN lam viec cho tat ca cac dean do 'Dieu Hanh' chu tri
SELECT NHANVIEN.HOTEN 
FROM NHANVIEN 
JOIN PHANCONG ON NHANVIEN.MANV = PHANCONG.MANV 
JOIN DEAN ON PHANCONG.MADA = DEAN.MADA
JOIN PHONGBAN ON DEAN.MAPHG = PHONGBAN.MAPHG 
GROUP BY NHANVIEN.HOTEN 
HAVING COUNT(DISTINCT DEAN.MADA ) = (SELECT COUNT(DISTINCT DEAN.MADA)
	FROM DEAN 
	JOIN PHANCONG ON DEAN.MADA = PHANCONG.MADA
	JOIN NHANVIEN ON PHANCONG.MANV = NHANVIEN.MANV
	JOIN PHONGBAN ON DEAN.MAPHG = PHONGBAN.MAPHG
	WHERE TENPHG = 'Dieu Hanh' )

-- TENPHG, HOTENTRGPHG cua phong ban co dong nhan vien nhat 
SELECT TOP 1 WITH TIES PHONGBAN.TENPHG, NHANVIEN.HOTEN AS HOTENTRUONGPHONG 
FROM PHONGBAN
JOIN NHANVIEN ON PHONGBAN.MAPHG = NHANVIEN.MAPHG 
GROUP BY PHONGBAN.TENPHG, NHANVIEN.HOTEN
ORDER BY COUNT(NHANVIEN.MANV) DESC -- GIAM DAN




