CREATE DATABASE DETHI
USE DETHI

CREATE TABLE CANGBIEN (
	SHCB NVARCHAR(5) PRIMARY KEY,
	TENCANG NVARCHAR(50),
	TINHTP NVARCHAR(30),
	LOAICB NVARCHAR(10)
)
 
CREATE TABLE TAU (
	SOIMO INT PRIMARY KEY,
	TENTAU NVARCHAR(50),
	CONGDUNG NVARCHAR(100),
	TONGCS INT
)

CREATE TABLE BENCANG (
	MABC NVARCHAR(10) PRIMARY KEY,
	SHCB NVARCHAR(5) FOREIGN KEY REFERENCES CANGBIEN(SHCB),
	TENBC NVARCHAR(50),
	SLTMAX INT
)

CREATE TABLE CAPCANG (
	SOIMO INT FOREIGN KEY REFERENCES TAU(SOIMO),
	MABC NVARCHAR(10) FOREIGN KEY REFERENCES BENCANG(MABC),
	NGCAP SMALLDATETIME,
	NGDI SMALLDATETIME,
	PRIMARY KEY (SOIMO, MABC, NGCAP)
)

-- CAU 02
INSERT INTO CANGBIEN(SHCB, TENCANG, TINHTP, LOAICB) VALUES 
('CB107', N'Cảng biển Thừa Thiên Huế', N'Thừa Thiên Huế', N'Loại 3'),
('CB305', N'Cảng biển Vũng Tàu', N'Bà Rịa - Vũng Tàu', N'Loại 1'),
('CB211', N'Cảng biển Dung Quất', N'Quãng Ngãi', N'Loại 2');

INSERT INTO TAU(SOIMO, TENTAU, CONGDUNG, TONGCS) VALUES 
('8814225', 'APOLLO PACIFIC', N'Tàu chở khí dầu hóa lỏng', '3798'),
('9371127', 'AQUAMARINE', N'Tàu chở hàng tổng hợp', '3598'),
('9853955', 'PHU QUOC EXPRESS 4', N'Tàu khách', '2855');

INSERT INTO BENCANG(MABC, SHCB, TENBC, SLTMAX) VALUES
('BC94', 'CB107', N'Bến cảng Chân Mây', '28'),
('BC106', 'CB211', N'Bến cảng Sa Kỳ', '25'),
('BC224', 'CB305', N'Bến cảng quốc tế Thị Vải', '40');

INSERT INTO CAPCANG(SOIMO, MABC, NGCAP, NGDI) VALUES 
('8814225', 'BC94', '11/12/2020', '19/12/2020'),
('8814225', 'BC224', '21/12/2020', '27/12/2020'),
('9371127', 'BC224', '12/12/2020', '11/01/2021');

-- CAU 03
ALTER TABLE CANGBIEN 
ADD CONSTRAINT LOAICB_CK CHECK(LOAICB IN (N'Loại 1', N'Loại 2', N'Loại 3'))

-- CAU 04
GO 
CREATE TRIGGER RANGBUOCGIAOHANG
ON CAPCANG 
FOR INSERT, UPDATE 
AS BEGIN 
IF EXISTS (
	SELECT 1
	FROM CAPCANG CC, INSERTED INS
	WHERE CC.SOIMO = INS.SOIMO
	AND CC.MABC <> INS.MABC 
	AND


-- CAU 05
SELECT TAU.SOIMO, TAU.TENTAU 
FROM TAU
JOIN CAPCANG CC ON TAU.SOIMO = CC.SOIMO
JOIN BENCANG BC ON CC.MABC = BC.MABC
JOIN CANGBIEN CB ON BC.SHCB = CB.SHCB 
WHERE LOAICB = N'Loại 3' 
ORDER BY TAU.TONGCS ASC

-- CAU 06
SELECT TOP 1 CB.SHCB, COUNT(DISTINCT CC.SOIMO) AS SOLUONG
FROM CANGBIEN CB
JOIN BENCANG BC ON CB.SHCB = BC.SHCB 
JOIN CAPCANG CC ON BC.MABC = CC.MABC 
WHERE LOAICB = N'Loại 1'
GROUP BY CB.SHCB
ORDER BY SOLUONG DESC;

-- CAU 07 
SELECT CB.SHCB 
FROM CANGBIEN CB 
JOIN BENCANG BC ON CB.SHCB = BC.SHCB 
JOIN CAPCANG CC ON BC.MABC = CC.MABC 
JOIN TAU ON CC.SOIMO = TAU.SOIMO 
WHERE CONGDUNG = 'Tàu khách'
EXCEPT 
SELECT CB.SHCB 
FROM CANGBIEN CB 
JOIN BENCANG BC ON CB.SHCB = BC.SHCB 
JOIN CAPCANG CC ON BC.MABC = CC.MABC 
JOIN TAU ON CC.SOIMO = TAU.SOIMO 
WHERE CONGDUNG = 'Tàu chở hàng tổng hợp'

-- CAU 08 
SELECT TAU.SOIMO, TENTAU
FROM TAU 
JOIN CAPCANG CC ON TAU.SOIMO = CC.SOIMO
WHERE NOT EXISTS (
	SELECT *
	FROM CANGBIEN CB
	WHERE LOAICB = N'Loại 3' AND NOT EXISTS (
		SELECT * 
		FROM BENCANG BC 
		WHERE BC.SHCB = CB.SHCB AND BC.MABC = CC.MABC ))

