CREATE DATABASE BAI2_QLGV
USE BAI2_QLGV 

CREATE TABLE KHOA (
	MAKHOA varchar(4) PRIMARY KEY,
	TENKHOA varchar(40),
	NGTLAP smalldatetime,
	TRGKHOA char(4),
)

CREATE TABLE MONHOC (
	MAMH varchar(10) PRIMARY KEY,
	TENMH varchar(40),
	TCLT tinyint,
	TCTH tinyint,
	MAKHOA varchar(4),
)

CREATE TABLE DIEUKIEN (
	MAMH varchar(10),
	MAMH_TRUOC varchar(10),
	PRIMARY KEY(MAMH, MAMH_TRUOC),
)

CREATE TABLE GIAOVIEN (
	MAGV char(4) PRIMARY KEY,
	HOTEN varchar(40),
	HOCVI varchar(10),
	HOCHAM varchar(10),
	GIOITINH varchar(3),
	NGSINH smalldatetime,
	NGVL smalldatetime,
	HESO numeric(4,2),
	MUCLUONG money,
	MAKHOA varchar(4),
)

CREATE TABLE LOP (
	MALOP char(3) PRIMARY KEY,
	TENLOP varchar(40),
	TRGLOP char(5),
	SISO tinyint,
	MAGVCN char(4),
)

CREATE TABLE HOCVIEN (
	MAHV char(5) PRIMARY KEY,
	HO varchar(40),
	TEN varchar(10),
	NGSINH smalldatetime,
	GIOITINH varchar(3),
	NOISINH varchar(40),
	MALOP char(3),
)

CREATE TABLE GIANGDAY (
	MALOP char(3),
	MAMH varchar(10),
	MAGV char(4),
	HOCKY tinyint,
	NAM smallint,
	TUNGAY smalldatetime,
	DENNGAY smalldatetime,
	PRIMARY KEY (MALOP, MAMH),
)

CREATE TABLE KETQUATHI (
	MAHV char(5),
	MAMH varchar(10),
	LANTHI tinyint,
	NGTHI smalldatetime,
	DIEM numeric(4,2),
	KQUA varchar(10),
	PRIMARY KEY (MAHV, MAMH, LANTHI),
)

ALTER TABLE MONHOC 
ADD CONSTRAINT FK_MONHOC_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE DIEUKIEN 
ADD CONSTRAINT FK_DIEUKIEN_MONHOC FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE DIEUKIEN 
ADD CONSTRAINT FK_DIEUKIEN_MONHOC_TRUOC FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH)

ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_GIAOVIEN_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE LOP 
ADD CONSTRAINT FK_LOP_HOCVIEN FOREIGN KEY (TRGLOP) REFERENCES HOCVIEN(MAHV)

ALTER TABLE LOP 
ADD CONSTRAINT FK_LOP_GIAOVIEN FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE HOCVIEN 
ADD CONSTRAINT FK_HOCVIEN_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)

ALTER TABLE GIANGDAY 
ADD CONSTRAINT FK_GIANGDAY_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GIANGDAY_MONHOC FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GIANGDAY_GIAOVIEN FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KETQUATHI_HOCVIEN FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV)

ALTER TABLE KETQUATHI 
ADD CONSTRAINT FK_KETQUATHI_MONHOC FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE KHOA 
ADD CONSTRAINT FK_KHOA_GIAOVIEN FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE HOCVIEN ADD GHICHU varchar(40)
ALTER TABLE HOCVIEN ADD DIEMTB numeric(4,2)
ALTER TABLE HOCVIEN ADD XEPLOAI varchar(4)

ALTER TABLE HOCVIEN ADD CONSTRAINT NGAYSINH_CK CHECK(YEAR(NGSINH) >= 18) 
ALTER TABLE GIANGDAY ADD CONSTRAINT TUNGAY_DENNGAY_CK CHECK (TUNGAY < DENNGAY)
ALTER TABLE GIAOVIEN ADD CONSTRAINT NGSINH_CK CHECK (YEAR(NGSINH) >= 22)
ALTER TABLE MONHOC ADD CONSTRAINT TCLT_TCTH_CK CHECK ((TCLT - TCTH <=3) OR (TCTH - TCLT <= 3))

INSERT INTO HOCVIEN (MAHV, HO, TEN, NGSINH, MALOP) 
VALUES
('K1101', 'Nguyen Van', 'A', '1986-01-27', 'K11'),
('K1102', 'Tran Ngoc', 'Han', '1986-03-14', 'K11'),
('K1103', 'Ha Duy', 'Lap', '1986-04-18', 'K11'),
('K1104', 'Tran Ngoc', 'Linh', '1986-03-30', 'K11'),
('K1105', 'Tran Minh', 'Long', '1986-02-27', 'K11'),
('K1106', 'Le Nhat', 'Minh', '1986-01-24', 'K11'),
('K1107', 'Nguyen Nhu', 'Nhut', '1986-01-27', 'K11'),
('K1108', 'Nguyen Manh', 'Tam', '1986-02-27', 'K11'),
('K1109', 'Phan Thi Thanh', 'Tam', '1986-01-27', 'K11'),
('K1110', 'Le Hoai', 'Thuong', '1986-02-05', 'K11'),
('K1111', 'Le Ha', 'Vinh', '1986-12-25', 'K11'),

('K1201', 'Nguyen Van', 'B', '1986-02-11', 'K12'),
('K1202', 'Nguyen Thi Kim', 'Duyen', '1986-01-18', 'K12'),
('K1203', 'Tran Thi Kim', 'Duyen', '1986-09-17', 'K12'),
('K1204', 'Truong My', 'Hanh', '1986-05-19', 'K12'),
('K1205', 'Nguyen Thanh', 'Nam', '1986-04-17', 'K12'),
('K1206', 'Nguyen Thi Truc', 'Thanh', '1986-03-04', 'K12'),
('K1207', 'Tran Thi Bich', 'Thuy', '1986-02-08', 'K12'),
('K1208', 'Huynh Thi Kim', 'Trieu', '1986-04-08', 'K12'),
('K1209', 'Pham Thanh', 'Trieu', '1986-02-23', 'K12'),
('K1210', 'Ngo Thanh', 'Tuan', '1986-02-14', 'K12'),
('K1211', 'Do Thi', 'Xuan', '1986-03-09', 'K12'),
('K1212', 'Le Thi Phi', 'Yen', '1986-03-12', 'K12'),

('K1301', 'Nguyen Thi Kim', 'Cuc', '1986-06-09', 'K13'),
('K1302', 'Truong Thi My', 'Hien', '1986-03-18', 'K13'),
('K1303', 'Le Duc', 'Hien', '1986-03-21', 'K13'),
('K1304', 'Le Quang', 'Hien', '1986-04-18', 'K13'),
('K1305', 'Le Thi', 'Huong', '1986-03-27', 'K13'),
('K1306', 'Nguyen Thai', 'Huu', '1986-03-30', 'K13'),
('K1307', 'Tran Minh', 'Man', '1986-05-28', 'K13'),
('K1308', 'Nguyen Hieu', 'Nghia', '1986-04-08', 'K13'),
('K1309', 'Nguyen Trung', 'Nghia', '1987-01-18', 'K13'),
('K1310', 'Tran Thi Hong', 'Tham', '1986-04-22', 'K13'),
('K1311', 'Tran Minh', 'Thuc', '1986-04-04', 'K13'),
('K1312', 'Nguyen Thi Kim', 'Yen', '1986-09-07', 'K13');

SELECT HV.MAHV, HV.HO, HV.TEN, HV.NGSINH, HV.MALOP
FROM HOCVIEN HV 
JOIN LOP L ON HV.MAHV = L.TRGLOP

INSERT INTO KETQUATHI(MAHV, MAMH, LANTHI, NGTHI, DIEM, KQUA)
VALUES
('K1202', 'CTRR', 2, '2006-05-20', 4.00, 'Khong Dat'),
('K1202', 'CTRR', 3, '2006-06-30', 6.25, 'Dat'),
('K1203', 'CSDL', 1, '2006-07-20', 9.25, 'Dat'),
('K1203', 'CTDLGT', 1, '2006-12-28', 9.50, 'Dat'),
('K1203', 'THDC', 1, '2006-05-20', 10.00, 'Dat'),
('K1203', 'CTRR', 1, '2006-05-13', 10.00, 'Dat'),
('K1204', 'CSDL', 1, '2006-07-20', 8.50, 'Dat'),
('K1204', 'CTDLGT', 1, '2006-12-28', 6.75, 'Dat'),
('K1204', 'THDC', 1, '2006-05-20', 4.00, 'Khong Dat'),
('K1204', 'CTRR', 1, '2006-05-13', 6.00, 'Dat'),
('K1301', 'CSDL', 1, '2006-12-20', 4.25, 'Khong Dat'),
('K1301', 'CTDLGT', 1, '2006-07-25', 8.00, 'Dat'),
('K1301', 'THDC', 1, '2006-05-20', 7.75, 'Dat'),
('K1301', 'CTRR', 1, '2006-05-13', 8.00, 'Dat'),
('K1302', 'CSDL', 1, '2006-12-20', 6.75, 'Dat'),
('K1302', 'CTDLGT', 1, '2006-07-25', 5.00, 'Dat'),
('K1302', 'THDC', 1, '2006-05-20', 8.00, 'Dat'),
('K1302', 'CTRR', 1, '2006-05-13', 8.50, 'Dat'),
('K1303', 'CSDL', 1, '2006-12-20', 4.00, 'Khong Dat'),
('K1303', 'CTDLGT', 1, '2006-07-25', 4.50, 'Khong Dat'),
('K1303', 'CTDLGT', 2, '2006-08-07', 4.00, 'Khong Dat'),
('K1303', 'CTDLGT', 3, '2006-08-15', 4.25, 'Khong Dat'),
('K1303', 'THDC', 1, '2006-05-20', 4.50, 'Khong Dat'),
('K1303', 'CTRR', 1, '2006-05-13', 3.25, 'Khong Dat'),
('K1303', 'CTRR', 2, '2006-05-20', 5.00, 'Dat'),
('K1304', 'CSDL', 1, '2006-12-20', 7.75, 'Dat'),
('K1304', 'CTDLGT', 1, '2006-07-25', 9.75, 'Dat'),
('K1304', 'THDC', 1, '2006-05-20', 5.50, 'Dat'),
('K1304', 'CTRR', 1, '2006-05-13', 5.00, 'Dat'),
('K1305', 'CSDL', 1, '2006-12-20', 9.25, 'Dat'),
('K1305', 'CTDLGT', 1, '2006-07-25', 10.00, 'Dat'),
('K1305', 'THDC', 1, '2006-05-20', 8.00, 'Dat'),
('K1305', 'CTRR', 1, '2006-05-13', 10.00, 'Dat');

--Bai 2--
UPDATE GIAOVIEN
SET HESO = HESO + 0.2
WHERE MAGV IN (
    SELECT TRGKHOA
    FROM KHOA
    WHERE TRGKHOA IS NOT NULL
);

UPDATE HOCVIEN
SET DIEMTB = (
    SELECT AVG(KQ.DIEM)
    FROM KETQUATHI AS KQ
    WHERE KQ.MAHV = HOCVIEN.MAHV
      AND KQ.LANTHI = (
          SELECT MAX(KQ2.LANTHI)
          FROM KETQUATHI AS KQ2
          WHERE KQ2.MAHV = KQ.MAHV
            AND KQ2.MAMH = KQ.MAMH
      )
);

UPDATE HOCVIEN
SET GHICHU = 'Cam thi'
WHERE MAHV IN (
    SELECT MAHV
    FROM KETQUATHI
    WHERE LANTHI = 3 AND DIEM < 5
);

UPDATE HOCVIEN
SET XEPLOAI = 
    CASE 
        WHEN DIEMTB >= 9 THEN 'XS'
        WHEN DIEMTB >= 8 THEN 'G'
        WHEN DIEMTB >= 6.5 THEN 'K'
        WHEN DIEMTB >= 5 THEN 'TB'
        ELSE 'Y'
    END;

--Bai 3--
SELECT DISTINCT MH.TENMH
FROM MONHOC MH
JOIN GIANGDAY GD ON MH.MAMH = GD.MAMH
JOIN GIAOVIEN GV ON GD.MAGV = GV.MAGV
WHERE GV.HOTEN = 'Tran Tam Thanh'
  AND GD.HOCKY = 1
  AND GD.NAM = 2006;

SELECT DISTINCT MH.MAMH, MH.TENMH
FROM MONHOC MH
JOIN GIANGDAY GD ON MH.MAMH = GD.MAMH
JOIN LOP L ON GD.MALOP = L.MALOP
JOIN GIAOVIEN GV ON GD.MAGV = GV.MAGV
WHERE L.MALOP = 'K11'
  AND GV.MAGV = L.MAGVCN
  AND GD.HOCKY = 1
  AND GD.NAM = 2006;

SELECT DISTINCT HV.HO, HV.TEN
FROM HOCVIEN HV
JOIN LOP L ON HV.MAHV = L.TRGLOP
JOIN GIANGDAY GD ON L.MALOP = GD.MALOP
JOIN MONHOC MH ON GD.MAMH = MH.MAMH
JOIN GIAOVIEN GV ON GD.MAGV = GV.MAGV
WHERE GV.HOTEN = 'Nguyen To Lan'
  AND MH.TENMH = 'Co So Du Lieu';

SELECT TRUOC.MAMH, TRUOC.TENMH
FROM DIEUKIEN DK
JOIN MONHOC SAU ON DK.MAMH = SAU.MAMH
JOIN MONHOC TRUOC ON DK.MAMH_TRUOC = TRUOC.MAMH
WHERE SAU.TENMH = 'Co So Du Lieu';

SELECT MH.MAMH, MH.TENMH
FROM MONHOC MH
JOIN DIEUKIEN DK ON MH.MAMH = DK.MAMH
JOIN MONHOC TRUOC ON DK.MAMH_TRUOC = TRUOC.MAMH
WHERE TRUOC.TENMH = 'CTRR';

--Bai 5--
SELECT GV.HOTEN
FROM GIAOVIEN GV
JOIN GIANGDAY GD ON GV.MAGV = GD.MAGV
WHERE GD.MAMH = 'CTRR'
  AND GD.HOCKY = 1
  AND GD.NAM = 2006
  AND GD.MALOP IN ('K11', 'K12')
GROUP BY GV.HOTEN

SELECT HV.MAHV, HV.HO, HV.TEN
FROM HOCVIEN HV
JOIN KETQUATHI KQ1 ON HV.MAHV = KQ1.MAHV
WHERE KQ1.MAMH = 'CSDL'
  AND KQ1.LANTHI = 1
  AND KQ1.DIEM < 5
  AND NOT EXISTS (
      SELECT 1
      FROM KETQUATHI KQ2
      WHERE KQ2.MAHV = HV.MAHV
        AND KQ2.MAMH = 'CSDL'
        AND KQ2.LANTHI > 1
);

SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
    SELECT 1
    FROM GIANGDAY GD
    WHERE GD.MAGV = GV.MAGV
);

SELECT GV.MAGV, GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (
    SELECT 1
    FROM MONHOC MH
    WHERE MH.MAKHOA = GV.MAKHOA
      AND EXISTS (
          SELECT 1
          FROM GIANGDAY GD
          WHERE GD.MAGV = GV.MAGV
            AND GD.MAMH = MH.MAMH
      )
);

SELECT HV.HO, HV.TEN
FROM HOCVIEN HV
WHERE HV.MALOP = 'K11'
  AND (
        HV.MAHV IN (
            SELECT MAHV
            FROM KETQUATHI
            WHERE KQUA = 'Khong dat'
            GROUP BY MAHV, MAMH
            HAVING COUNT(*) > 3
        )
        OR
        HV.MAHV IN (
            SELECT MAHV
            FROM KETQUATHI
            WHERE MAMH = 'CTRR'
              AND LANTHI = 2
              AND DIEM = 5
        )
      );

SELECT GV.HOTEN
FROM GIANGDAY GD
JOIN GIAOVIEN GV ON GD.MAGV = GV.MAGV
JOIN MONHOC MH ON GD.MAMH = MH.MAMH
WHERE MH.MAMH = 'CTRR'
GROUP BY GV.HOTEN, GD.HOCKY, GD.NAM
HAVING COUNT(DISTINCT GD.MALOP) >= 2;

SELECT HV.MAHV, HV.HO, HV.TEN, KQ.DIEM
FROM HOCVIEN HV
JOIN KETQUATHI KQ ON HV.MAHV = KQ.MAHV
JOIN MONHOC MH ON KQ.MAMH = MH.MAMH
WHERE MH.MAMH = 'CSDL'
  AND KQ.LANTHI = (
      SELECT MAX(KQ2.LANTHI)
      FROM KETQUATHI KQ2
      WHERE KQ2.MAHV = HV.MAHV
        AND KQ2.MAMH = KQ.MAMH
);

SELECT HV.MAHV, HV.HO, HV.TEN, MAX(KQ.DIEM) AS KETQUATOTNHAT
FROM HOCVIEN HV
JOIN KETQUATHI KQ ON HV.MAHV = KQ.MAHV
JOIN MONHOC MH ON KQ.MAMH = MH.MAMH
WHERE MH.TENMH = 'Co so du lieu'
GROUP BY HV.MAHV, HV.HO, HV.TEN;

--LAB 4-- 
--BAI 2--
SELECT MAKHOA, TENKHOA
FROM KHOA 
WHERE NGTLAP = (SELECT MIN(NGTLAP) FROM KHOA)

SELECT COUNT(*) 'So giao vien co hoc ham GS - PGS'
FROM GIAOVIEN
WHERE HOCHAM IN ('GS','PGS')

SELECT MAKHOA, HOCVI, COUNT(*) 'So giao vien co hoc vi trong moi khoa'
FROM GIAOVIEN
GROUP BY MAKHOA, HOCVI 
ORDER BY MAKHOA 

SELECT MAMH, KQUA, COUNT(*) 'So luong hoc vien theo ket qua'
FROM KETQUATHI
GROUP BY KQUA, MAMH
ORDER BY MAMH

SELECT GIANGDAY.MAGV, HOTEN
FROM GIANGDAY, LOP, GIAOVIEN
WHERE GIANGDAY.MALOP = LOP.MALOP
    AND GIANGDAY.MAGV = GIAOVIEN.MAGV
    AND GIAOVIEN.MAGV = LOP.MAGVCN 

SELECT HO, TEN 
FROM LOP, HOCVIEN 
WHERE LOP.TRGLOP = HOCVIEN.MAHV 
    AND LOP.SISO = (SELECT MAX(SISO) FROM LOP)

SELECT HO, TEN 
FROM LOP, HOCVIEN, KETQUATHI
WHERE LOP.TRGLOP = HOCVIEN.MAHV
    AND HOCVIEN.MAHV = KETQUATHI.MAHV 
    AND KQUA = 'Khong dat' 
GROUP BY TRGLOP, HO, TEN 
HAVING COUNT(*) > 3

--BAI 4--
SELECT TOP 1 WITH TIES HOCVIEN.MAHV, HO, TEN 
FROM HOCVIEN, KETQUATHI
WHERE HOCVIEN.MAHV = KETQUATHI.MAHV
    AND DIEM >= 9
GROUP BY HOCVIEN.MAHV, HO, TEN 
ORDER BY COUNT(*) DESC 

SELECT TOP 1 WITH TIES HOCVIEN.MAHV, HO, TEN 
FROM HOCVIEN, LOP, KETQUATHI
WHERE HOCVIEN.MAHV = KETQUATHI.MAHV
    AND HOCVIEN.MALOP = LOP.MALOP
    AND DIEM >= 9
GROUP BY LOP.MALOP, HOCVIEN.MAHV, HO, TEN
ORDER BY COUNT(*) DESC

SELECT MAGV, COUNT (DISTINCT MAMH) 'So mon hoc', COUNT(DISTINCT MALOP) 'So lop'
FROM GIANGDAY
GROUP BY MAGV

SELECT HOCKY, NAM, A.MAGV, HOTEN 
FROM GIAOVIEN, (SELECT HOCKY, NAM, MAGV, RANK() OVER (PARTITION BY HOCKY, NAM 
                    ORDER BY COUNT(*) DESC) AS XEPHANG
                FROM GIANGDAY 
                GROUP BY HOCKY, NAM, MAGV ) AS A
WHERE A.MAGV = GIAOVIEN.MAGV AND XEPHANG = 1 
ORDER BY NAM, HOCKY 

SELECT TOP 1 WITH TIES MONHOC.MAMH, TENMH
FROM KETQUATHI, MONHOC
WHERE MONHOC.MAMH = KETQUATHI.MAMH 
    AND LANTHI = 1
    AND KQUA = 'Khong dat'
GROUP BY MONHOC.MAMH, TENMH
ORDER BY COUNT(*) DESC 

SELECT DISTINCT HOCVIEN.MAHV, HO, TEN 
FROM HOCVIEN, KETQUATHI 
WHERE HOCVIEN.MAHV = KETQUATHI.MAHV
    AND NOT EXISTS (
    SELECT * FROM KETQUATHI 
    WHERE LANTHI = 1
    AND KQUA = 'Dat'
    AND MAHV = HOCVIEN.MAHV 
    )


SELECT DISTINCT HOCVIEN.MAHV, HO, TEN 
FROM HOCVIEN, KETQUATHI 
WHERE HOCVIEN.MAHV = KETQUATHI.MAHV
    AND NOT EXISTS (
    SELECT * FROM KETQUATHI 
    WHERE LANTHI = (
        SELECT MAX(LANTHI) 
        FROM KETQUATHI 
        WHERE MAHV = HOCVIEN.MAHV 
        GROUP BY MAHV)
    AND KQUA = 'Khong Dat'
    AND MAHV = HOCVIEN.MAHV 
    )

SELECT DISTINCT MAHV, HO, TEN
FROM HOCVIEN
WHERE NOT EXISTS (
        SELECT * FROM MONHOC 
        WHERE NOT EXISTS (
            SELECT *
            FROM KETQUATHI
            WHERE KETQUATHI.MAMH = MONHOC.MAMH
                AND KETQUATHI.MAHV = HOCVIEN.MAHV
                AND LANTHI = 1
                AND KQUA = 'Khong dat'
        )
)

SELECT DISTINCT MAHV, HO, TEN
FROM HOCVIEN
WHERE NOT EXISTS (
        SELECT * FROM MONHOC 
        WHERE NOT EXISTS (
            SELECT *
            FROM KETQUATHI
            WHERE KETQUATHI.MAMH = MONHOC.MAMH
                AND KETQUATHI.MAHV = HOCVIEN.MAHV
                AND LANTHI = (SELECT MAX(LANTHI) FROM KETQUATHI WHERE MAHV = HOCVIEN.MAHV GROUP BY MAHV)
                AND KQUA = 'Khong dat'
        )
)

SELECT MAMH, MAHV, HO, TEN
FROM (
      SELECT MAMH, HOCVIEN.MAHV, HO, TEN, RANK() OVER (PARTITION BY MAMH ORDER BY MAX(DIEM) DESC) AS XEPHANG 
      FROM HOCVIEN, KETQUATHI
      WHERE
            HOCVIEN.MAHV = KETQUATHI.MAHV
            AND LANTHI = (SELECT MAX(LANTHI) FROM KETQUATHI WHERE MAHV = HOCVIEN.MAHV GROUP BY MAHV)
      GROUP BY
            MAMH, HOCVIEN.MAHV, HO, TEN ) AS A
WHERE XepHang = 1
