CREATE DATABASE THITHUCHANHDE1
USE THITHUCHANHDE1

CREATE TABLE TACGIA (
	MaTG char(5) PRIMARY KEY,
	HoTen varchar(20),
	DiaChi varchar(50),
	NgSinh smalldatetime,
	SoDT varchar(15)
	)

CREATE TABLE SACH (
	MaSach char(5) PRIMARY KEY,
	TenSach varchar(25),
	TheLoai varchar(25)
	)

CREATE TABLE TACGIA_SACH (
	MaTG char(5) FOREIGN KEY REFERENCES TACGIA(MaTG),
	MaSach char(5) FOREIGN KEY REFERENCES SACH(MaSach),
	PRIMARY KEY (MaTG, MaSach)
	)

CREATE TABLE PHATHANH (
	MaPH char(5) PRIMARY KEY,
	MaSach char(5) FOREIGN KEY REFERENCES SACH(MaSach),
	NgayPH smalldatetime,
	SoLuong int,
	NhaXuatBan varchar(20)
	)

-- CAU 2.1
GO 
CREATE TRIGGER TG21
ON PHATHANH
FOR INSERT, UPDATE
AS 
BEGIN IF EXISTS (
	SELECT *
	FROM inserted INS
	JOIN PHATHANH PH ON INS.MaPH = PH.MaPH
	JOIN TACGIA_SACH TS ON INS.MaSach = TS.MaSach
	JOIN TACGIA TG ON TS.MaTG = TS.MaTG 
	WHERE INS.NgayPH > NgSinh 
	)
	BEGIN 
		ROLLBACK TRANSACTION 
	END
END

-- CAU 2.2 
GO 
CREATE TRIGGER TG22
ON SACH 
FOR INSERT, UPDATE 
AS
BEGIN IF EXISTS (
	SELECT INS.TheLoai, NhaXuatBan
	FROM inserted INS 
	JOIN SACH ON INS.MaSach = SACH.MaSach
	JOIN PHATHANH PH ON SACH.MaSach = PH.MaSach
	WHERE INS.TheLoai = N'Giáo khoa' AND NhaXuatBan = N'Giáo dục' 
	GROUP BY INS.TheLoai, NhaXuatBan
	)
	BEGIN 
		ROLLBACK TRANSACTION
	END 
END 

-- CAU 3.1
SELECT TG.MaTG, HoTen, SoDT
FROM TACGIA TG 
JOIN TACGIA_SACH TS ON TG.MaTG = TS.MaTG
JOIN SACH ON TS.MaSach = SACH.MaSach 
JOIN PHATHANH PH ON SACH.MaSach = PH.MaSach
WHERE TheLoai = N'Văn học' AND NhaXuatBan = N'Trẻ' 

-- CAU 3.2
SELECT TOP 1 WITH TIES NhaXuatBan
FROM PHATHANH PH 
JOIN SACH ON PH.MaSach = SACH.MaSach
HAVING COUNT(DISTINCT TheLoai)
ORDER BY 




